### ISSUE TITLE
Type of Graph

### ISSUE THREAD

**Issue by ethan-hoffman** [jcvdav/issues-lab#2]
I'm looking at the geom_jitter plot and I'm wondering if the width and alpha values are able to display all of the dataset values. Can you run the code and check to make sure width, alpha, aes, and show.legend work?

https://github.com/jcvdav/issues-lab/blob/09baf2901114686dac49d2d78fc6794601f7432d/got_issues.Rmd#L30

**Comment by jcvdav** [comment]
Thanks @ethan-hoffman - Just updated this!
